### ISSUE TITLE
Bug with angular-inviewport v4.0.0

### ISSUE THREAD

**Issue by neilime** [thisissoon/angular-scroll-collapse#28]
Hi,

I have an error after updating your package thisissoon/angular-inviewport to v4.0.0 :

> ERROR in node_modules/@thisissoon/angular-scroll-collapse/app/scroll-collapse/scroll-collapse.directive.d.ts(2,10): error TS2305: Module '".../node_modules/@thisissoon/angular-inviewport/thisissoon-angular-inviewport"' has no exported member 'WindowRef'.

Is it possible to fix it ?

Thank you

**Comment by edoparearyee** [comment]
Hi @neilime, thanks for bringing this to our attention. The current version isn't compatible with @thisissoon/angular-inviewport v4.0.0 as it includes a breaking change. 

Will update this package in due course to support it but until then you can use v3.x of @thisissoon/angular-inviewport

**Comment by neilime** [comment]
Thank you @edoparearyee
